# Generated by Django 4.1.7 on 2023-02-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
