# Generated by Django 4.1.7 on 2023-02-24 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_owner_delete_owners'),
        ('manage_carservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestocars',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cars'),
        ),
    ]
